ReadPicSubcatIdxJSONFile([
 {  "category" : "charcoal" , "subcategory" : "botanical" , "picarray" : ["0", "1", "3", "4", "6", "8", "12", "14", "17", "19", "20", "25"] }, 
 {  "category" : "oil painting" , "subcategory" : "impression" , "picarray" : ["2", "11"] }, 
 {  "category" : "charcoal" , "subcategory" : "abstract" , "picarray" : ["5", "21"] }, 
 {  "category" : "oil painting" , "subcategory" : "textured abstract" , "picarray" : ["7"] }, 
 {  "category" : "oil painting" , "subcategory" : "abstract" , "picarray" : ["9", "10", "27"] }, 
 {  "category" : "charcoal" , "subcategory" : "still life" , "picarray" : ["13"] }, 
 {  "category" : "oil painting" , "subcategory" : "palette knife" , "picarray" : ["15", "16"] }, 
 {  "category" : "oil charcoal" , "subcategory" : "mixed media" , "picarray" : ["18"] }, 
 {  "category" : "oil painting" , "subcategory" : "scenary" , "picarray" : ["22"] }, 
 {  "category" : "charcoal" , "subcategory" : "marine" , "picarray" : ["23"] }, 
 {  "category" : "charcoal" , "subcategory" : "pet animal" , "picarray" : ["24", "26"] }, 
 {  "category" : "watercolor" , "subcategory" : "botanical" , "picarray" : ["28", "31"] }, 
 {  "category" : "pencil sketch" , "subcategory" : "botanical" , "picarray" : ["29"] }, 
 {  "category" : "watercolor" , "subcategory" : "zoological" , "picarray" : ["30"] }, 
 {  "category" : "watercolor" , "subcategory" : "landscape" , "picarray" : ["32", "34"] }, 
 {  "category" : "pencil sketch" , "subcategory" : "human anatomy" , "picarray" : ["33"] }, 
 {  "category" : "pencil sketch" , "subcategory" : "portrait" , "picarray" : ["35"] }, 
 {  "category" : "watercolor" , "subcategory" : "food" , "picarray" : ["36"] } 
]);
