ReadshowPictureJSONFile([
{
"name": "Angels_trumpet_edited.jpeg", "namewmd": "Angels_trumpet_edited_wmd.jpg", "namecmp": "Angels_trumpet_edited_cmp.jpg", "title": "Angels trumpet", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Simply emphasizes grooves of the trumpet and veins of the leaves that make it come out real." },
{
"name": "Arum_lily_edited.jpeg", "namewmd": "Arum_lily_edited_wmd.jpg", "namecmp": "Arum_lily_edited_cmp.jpg", "title": "Arum lily", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "charcoal.html", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "This's a dry arum lily and is hardly sketched to show it's curves and sharp grooves." },
{
"name": "Backwaters_edited.jpg", "namewmd": "Backwaters_edited_wmd.jpg", "namecmp": "Backwaters_edited_cmp.jpg", "title": "Backwater", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "impression", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Presents a night view of a vibrant place of public attraction. This painting has a lot of texturing and Vincent Van Gogh inspired me to paint the sky like that." },
{
"name": "Blooming_ochid_edited.jpeg", "namewmd": "Blooming_ochid_edited_wmd.jpg", "namecmp": "Blooming_ochid_edited_cmp.jpg", "title": "Blooming ochid", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Light and dark tones are carefully sketched that make the orchid bloom." },
{
"name": "Brussels_sprout_edited.jpeg", "namewmd": "Brussels_sprout_edited_wmd.jpg", "namecmp": "Brussels_sprout_edited_cmp.jpg", "title": "Brussels sprout", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Softly shaded showing they're naturalness." },
{
"name": "Cinnamon_rolls_in_mini_bar_edited.jpeg", "namewmd": "Cinnamon_rolls_in_mini_bar_edited_wmd.jpg", "namecmp": "Cinnamon_rolls_in_mini_bar_edited_cmp.jpg", "title": "Cinnamon rolls in mini bar", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "abstract", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Still life made in abstract form." },
{
"name": "Citrus_edited.jpeg", "namewmd": "Citrus_edited_wmd.jpg", "namecmp": "Citrus_edited_cmp.jpg", "title": "Citrus", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "An accurate, detailed, embellished depiction of nature or contemporary life." },
{
"name": "Color_of_emotions_edited.jpeg", "namewmd": "Color_of_emotions_edited_wmd.jpg", "namecmp": "Color_of_emotions_edited_cmp.jpg", "title": "Color of emotions", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "textured abstract", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "This is based on a small study of colour psychology. I once read that the most beautiful things in the world can't be seen or touched, they've to be felt by heart and one of them is emotions. So I wanted to see and touch them in physical form which is expressed like this." },
{
"name": "Daffodil_edited.jpeg", "namewmd": "Daffodil_edited_wmd.jpg", "namecmp": "Daffodil_edited_cmp.jpg", "title": "Daffodil", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Shows naturalness and softness of the petals." },
{
"name": "Disorientation_edited.jpg", "namewmd": "Disorientation_edited_wmd.jpg", "namecmp": "Disorientation_edited_cmp.jpg", "title": "Disorientation", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "abstract", "context": "", "locationbased": "spain", "locationmade": "bangalore", "desc": "Depicts derangement of all senses and shows all forms of love, suffering and madness in an abstract form." },
{
"name": "Slot_canyon_edited.jpg", "namewmd": "Slot_canyon_edited_wmd.jpg", "namecmp": "Slot_canyon_edited_cmp.jpg", "title": "Slot canyon", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "400", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "abstract", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Depicts energetic and brilliant clustered field of reddish-brown over-laps making a canyon. Presents free and lyrical approach to colour as well." },
{
"name": "Flowers_pot_edited.jpg", "namewmd": "Flowers_pot_edited_wmd.jpg", "namecmp": "Flowers_pot_edited_cmp.jpg", "title": "Flower pot", "year": "", "currency": "", "price": "", "widthpx": "300", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "impression", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "It captures the vast range of tones in petals as they reflect and absorb light. Each flower contains all complexity and transcendent beauty of a large landscape. Their temporary urgency reminds to be present in the moment as they are. More than showing subtle colour shifts in light, it brings their texture to life through impressions." },
{
"name": "Gloxinia_edited.jpeg", "namewmd": "Gloxinia_edited_wmd.jpg", "namecmp": "Gloxinia_edited_cmp.jpg", "title": "Gloxinia", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "More prominence for the leaves of the flower. They're 3d texture is shown with thick boundaries." },
{
"name": "Grape_wine_edited.jpeg", "namewmd": "Grape_wine_edited_wmd.jpg", "namecmp": "Grape_wine_edited_cmp.jpg", "title": "Grape wine", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "still life", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Grape's are in abstract form and the sharpness of wine glass and bottle is shown accurately." },
{
"name": "Hollyhock_edited.jpeg", "namewmd": "Hollyhock_edited_wmd.jpg", "namecmp": "Hollyhock_edited_cmp.jpg", "title": "Hollyhock", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Depicts the depth and tones in petals that make it look very realistic." },
{
"name": "Into_The_Woods_edited.jpg", "namewmd": "Into_The_Woods_edited_wmd.jpg", "namecmp": "Into_The_Woods_edited_cmp.jpg", "title": "Into the woods", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "palette knife", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "A replica of one of Leonid Afremov's paintings depicting woods in abstract form." },
{
"name": "Night_At_The_Street_edited.jpg", "namewmd": "Night_At_The_Street_edited_wmd.jpg", "namecmp": "Night_At_The_Street_edited_cmp.jpg", "title": "Night at the street", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "300", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "palette knife", "context": "", "locationbased": "london", "locationmade": "bangalore", "desc": "A replica of one of Leonid Afremov's paintings made to understand colour combination and working with pallette knife better." },
{
"name": "Passion_flower_edited.jpeg", "namewmd": "Passion_flower_edited_wmd.jpg", "namecmp": "Passion_flower_edited_cmp.jpg", "title": "Passion flower", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Shows the softness of the leaves and sharp pollen grains." },
{
"name": "Pearl_oyster_edited.jpeg", "namewmd": "Pearl_oyster_edited_wmd.jpg", "namecmp": "Pearl_oyster_edited_cmp.jpg", "title": "Pearl oyster", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil charcoal", "subcategory": "mixed media", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "This appears to be virtually erasing any flaws or imperfections." },
{
"name": "Poisonous_mushrooms_edited.jpeg", "namewmd": "Poisonous_mushrooms_edited_wmd.jpg", "namecmp": "Poisonous_mushrooms_edited_cmp.jpg", "title": "Poisonous mushrooms", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "They're sketched in animated form." },
{
"name": "Protea_edited.jpeg", "namewmd": "Protea_edited_wmd.jpg", "namecmp": "Protea_edited_cmp.jpg", "title": "Protea", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Depicts prominent details of the plant along with sharp fur and softly shaded leaves that make it pretty." },
{
"name": "Scrub_oysters_edited.jpeg", "namewmd": "Scrub_oysters_edited_wmd.jpg", "namecmp": "Scrub_oysters_edited_cmp.jpg", "title": "Scrub oysters", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "abstract", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Shows different shades of charcoal and visualizes them to be having a glittering quality, like bathed in some sort of light." },
{
"name": "Spain_house_edited.jpg", "namewmd": "Spain_house_edited_wmd.jpg", "namecmp": "Spain_house_edited_cmp.jpg", "title": "Spain house", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "400", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "scenary", "context": "", "locationbased": "spain", "locationmade": "bangalore", "desc": "Represents natural scenery as a subject matter or replicates it's obvious beauty. Without telling any story, illustrating an idea or conceptualizing a metaphor, just a simple house of spain. It also demonstrates profound sense of perspective and depth." },
{
"name": "The_angry_fish_edited.jpeg", "namewmd": "The_angry_fish_edited_wmd.jpg", "namecmp": "The_angry_fish_edited_cmp.jpg", "title": "The angry fish", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "marine", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "This fish rejects imaginative idealisation in close observation of outward appearances." },
{
"name": "The_disobedient_rabbit_edited.jpeg", "namewmd": "The_disobedient_rabbit_edited_wmd.jpg", "namecmp": "The_disobedient_rabbit_edited_cmp.jpg", "title": "The disobedient rabbit", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "pet animal", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "A fat notorious rabbit who doesn't obey anyone as her expression shows. The folds in her fur are sketched smoothly." },
{
"name": "The_happy_cactus_edited.jpeg", "namewmd": "The_happy_cactus_edited_wmd.jpg", "namecmp": "The_happy_cactus_edited_cmp.jpg", "title": "The happy cactus", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "botanical", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Cactus should usually be sad because they're thorny and people keep distance from it, but this cactus was happy when a huge flower grew on it and became it's friend stabilizing it's mind." },
{
"name": "The_innocent_bunny_edited.jpeg", "namewmd": "The_innocent_bunny_edited_wmd.jpg", "namecmp": "The_innocent_bunny_edited_cmp.jpg", "title": "The innocent bunny", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "600", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "charcoal", "subcategory": "pet animal", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "Shows the simplicity in bunny's behaviour and his eyes are a bit too innocent." },
{
"name": "Whole_Of_Night_edited.jpg", "namewmd": "Whole_Of_Night_edited_wmd.jpg", "namecmp": "Whole_Of_Night_edited_cmp.jpg", "title": "Whole of night", "year": "", "currency": "", "price": "", "widthpx": "400", "heightpx": "400", "widthinch": "", "heightinch": "", "namepage": "", "categorypage": "", "category": "oil painting", "subcategory": "abstract", "context": "", "locationbased": "NA", "locationmade": "bangalore", "desc": "It's fun conveying energy and drama with big brushstrokes applied with freedom. Also capturing every part of night in this small canvas." }
]);
